branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: server-scavenger-dev
environment-defaults:
  server-scavenger-dev:
    branch: master
    repository: server-scavenger
global:
  application_name: server-scavenger
  branch: master
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: server-scavenger
  sc: git
  workspace_type: Application
